name: Liveblocks Room Cleanup

on: [push]

  # schedule:
  #   # Run every day at 1:00 UTC
  #   - cron: '0 1 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run cleanup script
      run: node cleanup-rooms.js
      env:
        LIVEBLOCKS_SECRET_KEY: ${{ secrets.LIVEBLOCKS_SECRET_KEY }}
